name: Test Action
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened]
    branches:
      - main
  issue_comment:
    types: [created]

permissions: write-all

jobs:
  check-perf:
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/ench')
    runs-on: ubuntu-latest
    name: Check performances
    steps:
      - name: Get PR branch
        uses: xt0rted/pull-request-comment-branch@v1
        id: comment-branch
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}
      - name: Check perf
        uses: ./ # Uses an action in the root directory
        with:
          github_ref: ${{ steps.comment-branch.outputs.head_ref }}
          influxdb_url: http://ziade.org:8086
          influxdb_token: ${{ secrets.INFLUXDB_TOKEN }}
          influxdb_org: tarek
          influxdb_bucket: benchmarks
