name: Test Action
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened]
    branches:
      - main
  issue_comment:
    types: [created]

permissions: write-all

jobs:
  check-perf:
    runs-on: ubuntu-latest
    name: Check performances
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check perf
        id: check_perf
        uses: ./ # Uses an action in the root directory
        with:
          influxdb_url: http://ziade.org:8086
          influxdb_token: ${{ secrets.INFLUXDB_TOKEN }}
          influxdb_org: tarek
          influxdb_bucket: benchmarks
